#!/usr/bin/env ansible-playbook
---
- hosts: headlessPi
  sudo: yes
  gather_facts: yes
  tasks:
    - name: Update repositories cache and install dnsmasq
      apt:
        name: dnsmasq
        update_cache: yes
        cache_valid_time: 3600
    - name: Update repositories cache and install hostapd
      apt:
        name: hostapd
        update_cache: yes
        cache_valid_time: 3600
    - name: Update repositories cache and install hostapd
      apt:
        name: pigpio
        update_cache: yes
        cache_valid_time: 3600
    - name: Remove builtin node-red
      apt:
        name: nodered
        state: absent
    - name: Remove builtin wolfram engine
      apt:
        name: wolfram-engine
        state: absent
    - name: Remove builtin libreoffice
      apt:
        name: libreoffice*
        state: absent
    - name: install update-headless
      copy:
        src: files/usr/local/bin/update-headless
        dest: /usr/local/bin/
        owner: root
        group: staff
        mode: 0755
    - name: install interfaces
      copy:
        src: files/etc/network/interfaces
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: 0644
    - name: install hosts
      copy:
        src: files/etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
    - name: install create-uap0
      copy:
        src: files/usr/local/bin/create-uap0
        dest: /usr/local/bin/create-uap0
        owner: root
        group: root
        mode: 0755
    - name: install nodesource apt list
      copy:
        src: files/etc/apt/sources.list.d/nodesource.list
        dest: /etc/apt/sources.list.d/nodesource.list
        owner: root
        group: root
        mode: 0644
    - name: install uap0 startup script
      copy:
        src: files/etc/init.d/create-uap0
        dest: /etc/init.d/create-uap0
        owner: root
        group: root
        mode: 0755
    - name: enable uap0 startup script
      service:
        name: create-uap0
        enabled: yes
    - name: install headlessPi
      git:
        repo: 'https://github.com/headlessPi/headlessPi.git'
        dest: /usr/local/headlessPi/app
        version: v0.0.1
    - name: Install packages based on package.json.
      npm:
        path: /usr/local/headlessPi/app
