#!/usr/bin/env ansible-playbook
---
- hosts: headlessPi
  sudo: yes
  gather_facts: yes
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
    - name: Update repositories cache and install dnsmasq
      apt:
        name: dnsmasq
        update_cache: yes
        cache_valid_time: 3600
    - name: Update repositories cache and install hostapd
      apt:
        name: hostapd
        update_cache: yes
        cache_valid_time: 3600
    - name: Update repositories cache and install pigpio
      apt:
        name: pigpio
        update_cache: yes
        cache_valid_time: 3600
    - name: install update-headless
      copy:
        src: files/usr/local/bin/update-headless
        dest: /usr/local/bin/
        owner: root
        group: staff
        mode: 0755
    - name: install interfaces
      copy:
        src: files/etc/network/interfaces
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: 0644
    - name: install hosts
      copy:
        src: files/etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
    - name: install hostapd.conf.bootstrap
      copy:
        src: files/etc/hostapd/hostapd.conf.bootstrap
        dest: /etc/hostapd/hostapd.conf.bootstrap
        owner: root
        group: root
        mode: 0644
    - name: Import the NodeSource GPG key into apt
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present
    - name: Add NodeSource deb repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main'
        state: present
    - name: Install Node.js
      apt:
        name: nodejs
        state: installed
        update_cache: yes
    - name: install uap0 startup script
      copy:
        src: files/etc/init.d/create-uap0
        dest: /etc/init.d/create-uap0
        owner: root
        group: root
        mode: 0755
    - name: enable uap0 startup script
      shell: update-rc.d create-uap0 defaults
    - name: install headlessPi startup script
      copy:
        src: files/etc/init.d/headlesspi
        dest: /etc/init.d/headlesspi
        owner: root
        group: root
        mode: 0755
    - name: enable headlesspi startup script
      shell: update-rc.d headlesspi defaults
    - name: install headlessPi
      git:
        repo: 'https://github.com/headlessPi/headlessPi.git'
        dest: /usr/local/headlessPi/app
        version: v0.0.3
      notify: restart headlesspi
    - name: Install packages based on package.json.
      npm:
        path: /usr/local/headlessPi/app
  handlers:
    - name: restart headlesspi
      service:
        name: headlesspi
        state: started
