#!/usr/bin/env ansible-playbook
---
- hosts: headlessPi
  sudo: yes
  gather_facts: yes
  tasks:
    - name: Update repositories cache and install dnsmasq
      apt:
        name: dnsmasq
        update_cache: yes
    - name: Update repositories cache and install hostapd
      apt:
        name: hostapd
        update_cache: yes
    - name: Remove builtin node-red
      apt:
        name: nodered
        state: absent
    - name: Remove builtin wolfram engine
      apt:
        name: wolfram-engine
        state: absent
    - name: Remove builtin libreoffice
      apt:
        name: libreoffice*
        state: absent
    - copy:
        src: files/update-headless
        dest: /usr/local/bin/
        owner: root
        group: staff
        mode: 0755
    - git:
        repo: 'https://github.com/headlessPi/headlessPi.git'
        dest: /usr/local/headlessPi/app
        version: v0.0.1
