#!/bin/sh
### BEGIN INIT INFO
# Provides:          create-uap0
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Bring up uap0 interface at boot time
# Description:       Bring up uap0 interface at boot time
### END INIT INFO

if [ ! -f /etc/hostapd/hostapd.conf ]; then
  cp /etc/hostapd/hostapd.conf.bootstrap /etc/hostapd/hostapd.conf
fi

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    iw dev wlan0 interface add uap0 type __ap
    service dnsmasq restart
    sysctl net.ipv4.ip_forward=1
    iptables -t nat -A POSTROUTING -s 10.10.10.0/24 ! -d 10.10.10.0/24 -j MASQUERADE
    ifup uap0
    service dnsmasq restart
    ;;
  stop)
    ifdown uap0
    iw dev uap0 del
    ;;
  *)
    echo "Usage: /etc/init.d/start-uap0 {start|stop}"
    exit 1
    ;;
esac

exit 0
