#! /bin/sh
# /etc/init.d/start-uap0
#

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    iw dev wlan0 interface add uap0 type __ap
    service dnsmasq restart
    sysctl net.ipv4.ip_forward=1
    iptables -t nat -A POSTROUTING -s 10.10.10.0/24 ! -d 10.10.10.0/24 -j MASQUERADE
    ifup uap0
    ;;
  stop)
    ifdown uap0
    iw dev uap0 del
    ;;
  *)
    echo "Usage: /etc/init.d/start-uap0 {start|stop}"
    exit 1
    ;;
esac

exit 0
